export const videos = [
  {
    id: 1,
    titre:
      "5 jours pour traverser la Corse à pied ! (La randonnée la plus dure d’Europe) GR20",
    chaine: "Inoxtag",
    nombre_vues: 46000000,
    logo_chaine: "logoInox.jpg",
    miniature: "corseInox.jpg",
    date_sortie: "2022-07-01",
    temps: "1:07:40",
  },
  {
    id: 2,
    titre: "Tout sur Tortues Ninja (1987)",
    chaine: "Bazar du Grenier",
    nombre_vues: 685000,
    logo_chaine: "logoBazar.jpg",
    miniature: "/Bazar.jpg",
    date_sortie: "2018-04-01",
    temps: "22:16",
  },
  {
    id: 3,
    titre:
      "Je prototype le dernier Dropdown de ma carrière. Et je te l’offre 🎁",
    chaine: "Mickadoule",
    nombre_vues: 887000,
    logo_chaine: "logoMicka.jpg",
    miniature: "Micka.jpg",
    date_sortie: "2022-07-01",
    temps: "07:05",
  },
  {
    id: 4,
    titre: "HOT ONES : Mister V sera-t-il meilleur qu'au GP Explorer ?",
    chaine: "Studio Bagel",
    nombre_vues: 1900000,
    logo_chaine: "logoBagel.jpg",
    miniature: "bagel.jpg",
    date_sortie: "2024-01-01",
    temps: "34:34",
  },
  {
    id: 5,
    chaine: "CYRILmp4",
    titre: "5€ pendant une journée en Amérique du Sud",
    nombre_vues: 370000,
    logo_chaine: "logoCyril.jpg",
    miniature: "cyril.jpg",
    date_sortie: "2024-03-03",
    temps: "1:07:40",
  },
];
