export const videos = [
  {
    id: "ZRJo0yJWdfY?si=8pb3KKEFq2BPgNvG",
    titre:
      "5 jours pour traverser la Corse à pied ! (La randonnée la plus dure d’Europe) GR20",
    chaine: "Inoxtag",
    nombre_vues: 46000000,
    logo_chaine: "logoInox.jpg",
    miniature: "corseInox.jpg",
    date_sortie: "2022-07-01",
    temps: "1:07:40",
    link: "https://www.youtube.com/embed/ZRJo0yJWdfY?si=ZP0yWiI_V4x20WKB",
  },
  {
    id: "jarbNjyux3s?si=a9faruxsC9dqj9P9",
    titre: "Tout sur Tortues Ninja (1987)",
    chaine: "Bazar du Grenier",
    nombre_vues: 685000,
    logo_chaine: "logoBazar.jpg",
    miniature: "/Bazar.jpg",
    date_sortie: "2018-04-01",
    temps: "22:16",
    link: "https://www.youtube.com/embed/jarbNjyux3s?si=mL-aj5Nm2TcD2BYL",
  },
  {
    id: "IxczEtQUFgg?si=Y2Ew24yDv9l5dJqC",
    titre:
      "Je prototype le dernier Dropdown de ma carrière. Et je te l’offre 🎁",
    chaine: "Mickadoule",
    nombre_vues: 887000,
    logo_chaine: "logoMicka.jpg",
    miniature: "Micka.jpg",
    date_sortie: "2022-07-01",
    temps: "07:05",
    link: "https://www.youtube.com/embed/IxczEtQUFgg?si=Y2Ew24yDv9l5dJqC",
  },
  {
    id: "B2eSchvRNJE?si=3l0A46J9UM_NbNVG",
    titre: "HOT ONES : Mister V sera-t-il meilleur qu'au GP Explorer ?",
    chaine: "Studio Bagel",
    nombre_vues: 1900000,
    logo_chaine: "logoBagel.jpg",
    miniature: "bagel.jpg",
    date_sortie: "2024-01-01",
    temps: "34:34",
    link: "https://www.youtube.com/embed/B2eSchvRNJE?si=3l0A46J9UM_NbNVG",
  },
  {
    id: "9dnZQC_PPNk?si=P4x8DePDIat62fBc",
    chaine: "CYRILmp4",
    titre: "5€ pendant une journée en Amérique du Sud",
    nombre_vues: 370000,
    logo_chaine: "logoCyril.jpg",
    miniature: "cyril.jpg",
    date_sortie: "2024-03-03",
    temps: "1:07:40",
    link: "https://www.youtube.com/embed/9dnZQC_PPNk?si=P4x8DePDIat62fBc",
  },
];
